### ISSUE TITLE
First screen: demo, read only mode pre-configured with columns

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#104] opened 2024-06-14 16:19 UTC
<img width="827" alt="Screenshot 2024-06-14 at 11 18 44 AM" src="https://github.com/damus-io/notedeck/assets/64376233/88f06324-3c82-4a1f-9a78-61d366910ed5">

**Comment by alltheseas** [comment] 2024-06-14 16:35
@kernelkind context here is that best practice on nostr is to let folk experience an app as fast as possible. First time notedeck is opened, it starts in demo, read only mode, so that the user can see and feel the experience, without the added friction of creating keys, or logging.

If they choose to do so, then the they can go through create keys or log in flow.

**Comment by kernelkind** [comment] 2024-06-26 16:43
This can be achieved with the default deck configuration #112

**Comment by kernelkind** [comment] 2024-11-27 16:59
duplicate of https://github.com/damus-io/notedeck/issues/446

**Closed by kernelkind** 2024-11-27 16:59 UTC
Labels: onboarding
