### ISSUE TITLE
hitbox does not work consistently on quote re-post

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#519] opened 2024-12-02 17:11 UTC
@ksedgwic

**Comment by ksedgwic** [comment] 2024-12-02 23:14
What I observe:

Starting from the quote-repost:
![quote-repost](https://github.com/user-attachments/assets/2f2aab86-4fb8-45d9-80b3-c3cdb48c0c6a)

If I click on the outer (the quote) I see this:
![click-on-outer-result](https://github.com/user-attachments/assets/ffab5bcb-5471-4b9d-a989-c066bac4391e)

And if I click on the inner (the quoted thing), I see this:
![click-on-inner-result](https://github.com/user-attachments/assets/f879f9fd-14f7-4114-9125-6f0028f9c63e)


@alltheseas What is the expected/desired behavior?

**Comment by jb55** [comment] 2024-12-03 00:27
try this note and click above the image:

```
./target/release/notedeck --datapath target/test --filter '{"ids":["d46bede59dbed638f379533b717898d88a037bb09932668ea3deec60d05070b3"]}'
```

**Comment by ksedgwic** [comment] 2024-12-03 00:56
Looks like it is related to images, but not related to quotes or reposts?

note1nvt09w87gzlvjgye36qzjmmap02x7rh406f6rgw03jx8pvhylwfqq3ct2w has the same issue

**Comment by jb55** [comment] 2024-12-03 01:17
@ksedgwic read again, click *above* the image, not on it. the hitbox does not seem to extend beyond the text. if you click the text and just above the image in my example post, it has different behavior.

**Comment by ksedgwic** [comment] 2024-12-03 17:50
@jb55 What should happen when you click on the image though?  Not academic, the space between the image and the quoted text is `image_carousel`

Related questions:
1. Should clicking on the quoted post's image go to the quoted post's thread?  (today it eats the event but does nothing)
2. Should clicking on the image carousel do the same thing as the image? (today it "passes" and we go to the quoting post's thread)

**Comment by ksedgwic** [comment] 2024-12-03 20:03
I think this is fixed by #537

**Comment by jb55** [comment] 2024-12-03 20:13
this happens on notes without a carousel, on that I just tried was :

```
./target/release/notedeck --datapath target/test --filter '{"ids":["0d8ce3a6f1c9315f91e68118b16cb714bd417ec56b18f6e67c8fa85091acc91d"]}'
```

try clicking on the quote repost but in an area with whitespace in the quote repost. if you don't click the text exactly it will open up the post not the quoted post.

**Comment by ksedgwic** [comment] 2024-12-03 21:38
I'm not following this example.  How many clicks are there?  Which click has an incorrect result?

**Comment by ksedgwic** [comment] 2024-12-03 21:44
Look, the problem isn't that the hitbox doesn't match the quoted note ... the problem is that the components of the quoted note are not associated with it (ie, the heirarchy appears disjoint/wrong).

The image fix above fixes some image related problems.

But the text-only quoted notes have an issue w/ `BlockType::Text` and `inline_note` in the `render_note_contents` function.  This code is complex and assumes understanding of some subtle `get_blocks_by_key` semantics which I don't understand (yet).

**Comment by jb55** [comment] 2024-12-03 21:48
The contents of the note shouldn't matter, as long as they are not registering any Senses. we only care about the hitbox of the inner frame of the `render_note_preview`

**Comment by ksedgwic** [comment] 2024-12-03 21:50
But the inner note doesn't include the inner notes image ... can we think about that first because it's simple?  My fix above includes the images in the inner note and solves that problem.

**Comment by ksedgwic** [comment] 2024-12-03 21:58
I don't understand the `inline_note` semantics in `render_note_contents` ... Shouldn't we be setting `inline_note` for `BlockType::Text`?

I think I'm missing a few pieces in my model ...

**Comment by ksedgwic** [comment] 2024-12-03 22:40
Your previous example:
> ./target/release/notedeck --datapath target/test --filter '{"ids":["0d8ce3a6f1c9315f91e68118b16cb714bd417ec56b18f6e67c8fa85091acc91d"]}'
> try clicking on the quote repost but in an area with whitespace (not text). if you don't click the text exactly it will open up the post not the quoted post.

If I click exactly on the word `cigarette` I go to the thread written by Trey Walsh ... this is wrong, right?  I should go to the thread written by Alex Gleason.

Meanwhile if I click anywhere else in the inner note I go to Alex's thread, which seems correct.

So I don't understand your comment above ... it seems backwards.  Where should clicking exactlky on the word "cigarette" go?

**Closed** 2024-12-04 01:58 UTC
Labels: ui, unexpected, testing
